name: Twitter RSS Bot

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  twitter-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci --legacy-peer-deps
      
    - name: Create .env file
      run: |
        echo "TWITTER_API_KEY=${{ secrets.TWITTER_API_KEY }}" >> .env
        echo "TWITTER_API_SECRET=${{ secrets.TWITTER_API_SECRET }}" >> .env
        echo "TWITTER_ACCESS_TOKEN=${{ secrets.TWITTER_ACCESS_TOKEN }}" >> .env
        echo "TWITTER_ACCESS_SECRET=${{ secrets.TWITTER_ACCESS_SECRET }}" >> .env
        echo "RSS_FEED_URL=https://alejandrooparodi.dev/rss.xml" >> .env
        echo "POSTED_ITEMS_FILE=./data/posted-items.json" >> .env
        echo "TWITTER_HANDLE=@alejandrooparodi" >> .env
        
    - name: Run Twitter RSS Bot
      run: npm run twitter-bot
      
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/posted-items.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Update posted items"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }} 